# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitChglog < Formula
  desc "CHANGELOG generator implemented in Go (Golang)."
  homepage "https://godoc.org/github.com/git-chglog/git-chglog"
  version "0.10.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_darwin_amd64.tar.gz"
    sha256 "d066237b3b1efecd38828c976cfcc65f3c29e0f954eb6fa295fcb35ec3b7e7e5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_amd64.tar.gz"
    sha256 "b3e08d302f3179c33b31e158cc566aa82e1bc121e0b0fc2baf6dbbf2166a6d79"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_armv6.tar.gz"
    sha256 "f2eea19b4c9d1a7f1f223266a2ebbdc39fdc581821dd4259276c4bf11b93f1c0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.10.0/git-chglog_0.10.0_linux_arm64.tar.gz"
    sha256 "0d9116db6dbd2e279c61c68f6705a323e4751af3bf1735c31868037664355e6a"
  end

  def install
    bin.install "git-chglog"
  end

  test do
    system "#{bin}/git-chglog --help"
  end
end
