# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitChglog < Formula
  desc "CHANGELOG generator implemented in Go (Golang)."
  homepage "https://godoc.org/github.com/git-chglog/git-chglog"
  version "0.11.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.11.0/git-chglog_0.11.0_darwin_amd64.tar.gz"
    sha256 "7f59e3c4c22eef7d794588341228f3a89e5bce09bc4bc421c415cc7c044336e3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.11.0/git-chglog_0.11.0_linux_amd64.tar.gz"
    sha256 "e30f3d4ec1f3ba91c717ec5200b738f18b8d6162067925d05d2d85f34e82d556"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.11.0/git-chglog_0.11.0_linux_armv6.tar.gz"
    sha256 "5fc7f9519c8105d94469bb4ed70ff2645d15de52acf4cfdabd401c5ed2256d24"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/git-chglog/git-chglog/releases/download/v0.11.0/git-chglog_0.11.0_linux_arm64.tar.gz"
    sha256 "f75653b0fbb6bd9eb7ecce4c3cbcaef38bf253c667b54138100004f0911cb87c"
  end

  def install
    bin.install "git-chglog"
  end

  test do
    system "#{bin}/git-chglog --help"
  end
end
